name: Update README.md Badges
  

on:
  schedule:
    # Runs daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  update-badges:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Update Badges
        uses: ./
        with:
          CREDLY_USER: 'steven-paradise' # Uses your GitHub username
# CREDLY_USER: ${{ steven-paradise }} # Uses your GitHub username
          NUMBER_LAST_BADGES: 0 # Show last 10 badges (0 = all)
          #readme_file: 'README.md'
          #credly_username: 'sparadise@mtb.com'


# steps:
#      - name: Update Credly Badges
#        uses: diceman175/README.md@v1.0
#        with:
#          credly_username: 'your-credly-username'
#          badge_size: '150x150'
#          badge_sort_by: 'issued'
#          github_api_url: 'https://api.github.com'
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          github_repo: ${{ github.repository }}
#          github_branch: 'main'
#          readme_file: 'README.md'
#          commit_message: 'Updated README with Credly badges'
